:schedule:
  web_sites_job:
    enabled: false
    cron: '0 0 */3 * * *'
    class: Crawler::WebSitesJob
    queue: crawlers
  twitter_accounts_job:
    enabled: false
    cron: '0 0 */3 * * *'
    class: Crawler::TwitterAccountsJob
    queue: crawlers
  mecab_dics_job:
    enabled: false
    cron: '0 0 0 * * *'
    class: MecabDicsJob
    queue: mecab_dics
  sitemaps_job:
    enabled: false
    cron: '0 0 0 * * *'
    class: SitemapsJob
    queue: sitemaps
  notifies_job:
    enabled: true
    cron: '30 * * * * *'
    class: NotifiesJob
    queue: notifies
  schedules_job:
    enabled: true
    cron: '30 * * * * *'
    class: SchedulesJob
    queue: notifies
  manual_save_relations_twitter_acccount:
    enabled: false
    class: Relations::TwitterAccountsJob
    queue: relations
:concurrency: 1
:queues:
  - crawlers
  - notifies
  - mecab_dics
  - sitemaps
  - collects
  - relations